// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Nestad$Type } from "./Nestad";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Nestad"]: Nestad$Type;
    ["contracts/Nestad.sol:Nestad"]: Nestad$Type;
  }

  interface ContractTypesMap {
    ["Nestad"]: GetContractReturnType<Nestad$Type["abi"]>;
    ["contracts/Nestad.sol:Nestad"]: GetContractReturnType<Nestad$Type["abi"]>;
  }
}
