// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Nestad1155$Type } from "./Nestad1155";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Nestad1155"]: Nestad1155$Type;
    ["contracts/Nestad1155.sol:Nestad1155"]: Nestad1155$Type;
  }

  interface ContractTypesMap {
    ["Nestad1155"]: GetContractReturnType<Nestad1155$Type["abi"]>;
    ["contracts/Nestad1155.sol:Nestad1155"]: GetContractReturnType<Nestad1155$Type["abi"]>;
  }
}
